version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  code:
    build: .
    ports:
      - "8000:5000"
  rabbitmq:
    image: "rabbitmq:3.9.13-management"
  metasploit:
     image: "metasploit-framework:latest"
volumes:
  db:
    driver: local
