version: '3.8'
services:
  code:
    build: .
    ports:
      - "8000:5000"
  #rabbitmq:
  #  image: rabbitmq:3.9.13-management
  msf:
    image: metasploitframework/metasploit-framework:latest
    environment:
      DATABASE_URL: postgres://user@password:5432/msfdb?pool=200&timeout=5
    links:
      - pgsql
    ports:
      - 8500-8600:8500-8600
    volumes:
      - $HOME/.msf4:/home/msf/.msf4

  pgsql:
    image: postgres:latest
    volumes:
      - $HOME/.msf4/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASS: pass
      POSTGRES_DB: msfdb

volumes:
  redis:
  redis-config:
  db:
    driver: local
